# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:09
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_squashed_0011'),
    ]

    operations = [
    ]
