# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:47
from django.db import migrations, models

import apps.push_notifications.fields


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0011_auto_20160303_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnsdevice',
            name='device_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='apnsdevice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='device_id',
            field=apps.push_notifications.fields.HexIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gcmdevice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
