# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-07 11:47
from django.db import migrations

from apps.instances.helpers import get_current_instance
from apps.instances.models import InstanceIndicator


def add_indicators(apps, schema_editor):
    APNSDevice = apps.get_model('push_notifications.APNSDevice')
    instance = get_current_instance()
    InstanceIndicator.objects.update_or_create(
        type=InstanceIndicator.TYPES.APNS_DEVICES_COUNT, instance=instance,
        defaults={'value': APNSDevice.objects.filter(is_active=True).count()})


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0013_auto_20160519_0847'),
    ]

    operations = [
        migrations.RunPython(add_indicators),
    ]
