# Generated by Django 2.0.6 on 2018-10-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0020_worklogentry_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worklogentry',
            unique_together={('left_boundary', 'right_boundary', 'location')},
        ),
    ]
