# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 13:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0011_instance_last_access'),
        ('metrics', '0018_cleanup_nulls')
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='noticed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL('CREATE INDEX instances_instance_last_access_idx'
                      ' ON instances_instance(last_access)'
                      ' WHERE noticed_at IS NULL;',
                      'DROP INDEX IF EXISTS instances_instance_last_access_idx;'),
        migrations.RunSQL('CREATE INDEX instances_instance_noticed_at_idx'
                      ' ON instances_instance(noticed_at)'
                      ' WHERE noticed_at IS NOT NULL;',
                      'DROP INDEX IF EXISTS instances_instance_noticed_at_idx;')
    ]
