# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 14:21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0012_instance_noticed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='database',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
