# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 08:07
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0015_auto_20160407_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='config',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
