# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:21
from django.db import migrations

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0016_instance_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='klasses_acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='klasses_acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={'*': ['get', 'list', 'update', 'delete']}, null=True),
        ),
    ]
