# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 10:38
from django.db import migrations

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0018_instance_channels_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='script_endpoints_acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='script_endpoints_acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={'*': ['get', 'list']}, null=True),
        ),
    ]
