# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 11:15
from django.db import migrations

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0019_instance_script_endpoints_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='groups_acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='groups_acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={'*': ['get', 'list', 'update', 'delete']}, null=True),
        ),
    ]
