# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 08:46
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0020_instance_groups_acl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='last_access',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='noticed_at',
        ),
    ]
