# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:50
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0021_remove_last_access_fields'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "instances_instance" ADD COLUMN "domains" varchar(253)[] DEFAULT array[]::varchar[] NOT NULL',
            'ALTER TABLE "instances_instance" DROP COLUMN "domains" CASCADE',
            [migrations.AddField(
                model_name='instance',
                name='domains',
                field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), default=[],
                                                                size=None),
            )]),
    ]
