# Generated by Django 2.0.6 on 2018-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0022_instance_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
