# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:48
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='query_args',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
