# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 11:21
import django.db.models.deletion
from django.core.files.storage import default_storage
from django.db import migrations, models

import apps.backups.models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backup_query_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='restore',
            name='archive',
            field=models.FileField(null=True, upload_to=apps.backups.models.restore_filename, storage=default_storage),
        ),
        migrations.AlterField(
            model_name='restore',
            name='backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backups.Backup'),
        ),
    ]
