# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 08:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_auto_20160308_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='status_info',
            field=models.TextField(blank=True),
        ),
    ]
