# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 06:43
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backup_status_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='restore',
            name='status_info',
            field=models.TextField(blank=True),
        ),
    ]
