# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:40
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_restore_status_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='details',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
