# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-19 14:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_backup_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
