# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:41
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_codebox_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=(None, None), db_index=True),
            preserve_default=False,
        ),
    ]
