# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:41
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_add_range_field_with_default'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE billing_subscription SET range=daterange("start", "end");
        """),
        migrations.RemoveField(
            model_name='subscription',
            name='end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(db_index=True),
        ),
    ]
