# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 11:07
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_remove_default_and_update_range_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(),
        ),
        migrations.RunSQL("""
CREATE INDEX subscription_range ON billing_subscription
USING GIST (range);
"""
        )
    ]
