# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:49
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0006_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='event',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='signals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
        migrations.RunSQL("""
CREATE INDEX trigger_event_signal  ON triggers_trigger
USING GIN(event, signals);
""", reverse_sql="""
DROP INDEX trigger_event_signal;
""")
    ]
