# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:50
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0007_event_and_signals'),
    ]

    operations = [
        migrations.RunSQL("""
UPDATE triggers_trigger AS tt
SET event=('source=>dataobject,class=>' || dk.name)::hstore,
signals=array[substring(tt.signal from 6)]
FROM data_klass AS dk
WHERE dk.id=tt.klass_id
        """, reverse_sql="")
    ]
