# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:16
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0008_event_data'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='trigger',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='signal',
        ),
    ]
