# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 12:43
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0010_socket_version'),
        ('triggers', '0009_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='socket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sockets.Socket'),
        ),
    ]
