# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 11:32
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0004_socketendpoint_metadata'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "sockets_socket" ADD COLUMN "config" TEXT DEFAULT \'{}\' NOT NULL',
            'ALTER TABLE "sockets_socket" DROP COLUMN "config" CASCADE',
            [migrations.AddField(
                model_name='socket',
                name='config',
                field=jsonfield.fields.JSONField(blank=True, default={}),
            )]),
    ]
