# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 11:39
from django.db import migrations

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0005_socket_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='installed_deps',
            field=apps.core.fields.NullableJSONField(blank=True, default={}, null=True),
        ),
    ]
