# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 13:54
from django.db import migrations

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0006_socket_installed_deps'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketendpoint',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='socketendpoint',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={}, null=True),
        ),
    ]
