# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 13:51
from django.core.files.storage import default_storage
from django.db import migrations, models

import apps.sockets.models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0007_socketendpoint_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='zip_file',
            field=models.FileField(blank=True, null=True,
                                   upload_to=apps.sockets.models.upload_custom_socket_file_to,
                                   storage=default_storage),
        ),
    ]
