# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-01 18:31
import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0010_socket_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', jsonfield.fields.JSONField(blank=True, default={})),
                ('handler_name', models.CharField(max_length=256)),
                ('handler', jsonfield.fields.JSONField(blank=True, default={})),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sockets.Socket')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterIndexTogether(
            name='sockethandler',
            index_together=set([('socket', 'handler_name')]),
        ),
    ]
