# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-10 13:12
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0014_socket_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='zip_file_list',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
