# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:11
import django.db.models.deletion
from django.db import migrations, models

import apps.core.backends.storage
import apps.core.fields
import apps.hosting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=256)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_is_live', apps.core.fields.LiveField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Hosting',
            },
        ),
        migrations.CreateModel(
            name='HostingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.TextField(max_length=300)),
                ('level', models.IntegerField(default=0)),
                ('size', models.IntegerField()),
                ('file_object', models.FileField(storage=apps.hosting.models.Hosting.get_storage(),
                                                 upload_to=apps.hosting.models.upload_hosting_file_to)),
                ('_is_live', apps.core.fields.LiveField(default=True)),
                ('hosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosting.Hosting')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'HostingFile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hostingfile',
            unique_together=set([('hosting', 'path', '_is_live')]),
        ),
    ]
