# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:03
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=253), default=[], size=None),
        ),
    ]
