# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 11:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0003_hosting_label_rename_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
