# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-27 10:16
from django.db import migrations, models


def set_default_and_remove_from_domains(apps, schema_editor):
    Hosting = apps.get_model("hosting", "Hosting")
    for hosting in Hosting.objects.all():
        if 'default' in hosting.domains:
            hosting.is_default = True
            hosting.domains.remove('default')
            hosting.save(update_fields=['domains', 'is_default'])


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_hosting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_default_and_remove_from_domains)
    ]
