# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 12:02
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosting', '0005_hosting_default'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE "hosting_hosting" ADD COLUMN "ssl_status" smallint DEFAULT 0 NOT NULL',
                          'ALTER TABLE "hosting_hosting" DROP COLUMN "ssl_status" CASCADE',
                          [migrations.AddField(
                              model_name='hosting',
                              name='ssl_status',
                              field=models.SmallIntegerField(choices=[(0, 'off'), (1, 'on')], default=0),
                          )]),
    ]
