# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-02 13:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0006_hosting_ssl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingfile',
            name='checksum',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
