# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 15:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_hosting_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='ssl_status_info',
            field=models.SmallIntegerField(choices=[(0, 'ok'), (1, 'invalid_domain'), (2, 'cname_not_set'), (3, 'wrong_cname'), (4, 'unknown')], default=2),
        ),
    ]
