# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 17:31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0009_hosting_ssl_status_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='ssl_status_info',
        ),
        migrations.AlterField(
            model_name='hosting',
            name='ssl_status',
            field=models.SmallIntegerField(choices=[(-1, 'checking'), (0, 'off'), (1, 'on'), (2, 'invalid_domain'), (3, 'cname_not_set'), (4, 'wrong_cname'), (5, 'unknown')], default=0),
        ),
    ]
