# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 14:55
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0010_removed_ssl_status_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosting',
            name='auth',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
