kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: platform-web
spec:
  minReplicas: ${WEB_MIN}
  maxReplicas: ${WEB_MAX}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: platform-web
  targetCPUUtilizationPercentage: 50
