# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 08:46
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_email_trgm_index'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE "admins_admin" ADD COLUMN "last_access" timestamp WITH TIME ZONE DEFAULT NOW() NOT NULL',
                          'ALTER TABLE "admins_admin" DROP COLUMN "last_access" CASCADE',
                          [migrations.AddField(
                              model_name='admin',
                              name='last_access',
                              field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
                              preserve_default=False,
                          )]),
        migrations.AddField(
            model_name='admin',
            name='noticed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
"""
CREATE INDEX admins_admin_noticed_at ON admins_admin
USING BTREE (noticed_at)
WHERE noticed_at IS NOT NULL;
"""
        )
    ]
