# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 12:09
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_add_last_access'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "admins_admin" ADD COLUMN "metadata" TEXT DEFAULT \'{}\' NOT NULL',
            'ALTER TABLE "admins_admin" DROP COLUMN "metadata" CASCADE',
            [migrations.AddField(
                model_name='admin',
                name='metadata',
                field=jsonfield.fields.JSONField(blank=True, default={}),
            )]),
    ]
