# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 12:25
from django.db import migrations, models


def runtimes_update(apps, schema_editor):
    CodeBox = apps.get_model('codeboxes.CodeBox')
    CodeBox.objects.filter(runtime_name='python').update(runtime_name='python_library_v4.2')
    CodeBox.objects.filter(runtime_name='nodejs').update(runtime_name='nodejs_library_v0.4')


class Migration(migrations.Migration):
    dependencies = [
        ('codeboxes', '0032_remove_codeboxschedule__is_live'),
    ]

    operations = [
        migrations.RunPython(runtimes_update),
        migrations.AlterField(
            model_name='codebox',
            name='runtime_name',
            field=models.CharField(max_length=40),
        ),
    ]
