# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 20:00
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0009_remove_obsolete_fields'),
        ('codeboxes', '0034_auto_add_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebox',
            name='socket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sockets.Socket'),
        ),
    ]
