# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 11:52
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0010_socket_version'),
        ('codeboxes', '0035_codebox_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeboxschedule',
            name='socket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sockets.Socket'),
        ),
    ]
