# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-15 22:23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeboxes', '0038_add_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codebox',
            unique_together=set([('socket', 'path')]),
        ),
        migrations.AlterIndexTogether(
            name='codebox',
            index_together=set([]),
        ),
    ]
