# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 10:38
import django.contrib.postgres.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0012_auto_20160225_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='webhook',
            name='_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhook',
            name='_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='webhook',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={}, null=True),
        ),
        migrations.RunSQL("""
CREATE INDEX webhook_acl_users ON webhooks_webhook
USING GIN (_users);

CREATE INDEX webhook_acl_groups ON webhooks_webhook
USING GIN (_groups);

CREATE INDEX webhook_acl_public ON webhooks_webhook
USING BTREE (_public) WHERE _public = true;
"""),
    ]
