# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 11:15
import django.contrib.postgres.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20151116_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='group',
            name='_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='group',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={}, null=True),
        ),
        migrations.RunSQL("""
CREATE INDEX group_acl_users ON users_group
USING GIN (_users);

CREATE INDEX group_acl_groups ON users_group
USING GIN (_groups);

CREATE INDEX group_acl_public ON users_group
USING BTREE (_public) WHERE _public = true;
""")
    ]
