# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:22
from django.db import connections, migrations, router


def add_default_acl(apps, schema_editor):
    Klass = apps.get_model('data.Klass')
    user_profile = Klass.objects.filter(name='user_profile').first()
    if user_profile is None:
        return

    DataObject = apps.get_model('data.DataObject')
    db = router.db_for_write(DataObject)
    cursor = connections[db].cursor()

    cursor.execute("""UPDATE data_dataobject SET acl='{"users": {"' || owner_id || '": ["read", "write"]}}'
    WHERE _klass_id=%s""", params=(user_profile.id,))


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0019_data_endpoint_acl'),
    ]

    operations = [
        migrations.RunPython(add_default_acl)
    ]
