# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:21
import django.contrib.postgres.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_default_acl_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='klass',
            name='_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='klass',
            name='_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='klass',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='klass',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={'*': ['read']}, null=True),
        ),
    ]
