# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 08:37
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_klass_acl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobject',
            name='channel_room',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True),
        ),
    ]
