# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_auto_20160606_0837'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE INDEX klass_acl_users ON data_klass
USING GIN (_users);

CREATE INDEX klass_acl_groups ON data_klass
USING GIN (_groups);

CREATE INDEX klass_acl_public ON data_klass
USING BTREE (_public) WHERE _public = true;
"""),
    ]
