# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:33
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0023_klass_acl_indexes'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE "data_klass" ADD COLUMN "visible" boolean DEFAULT true NOT NULL',
                          'ALTER TABLE "data_klass" DROP COLUMN "visible" CASCADE',
                          [migrations.AddField(
                              model_name='klass',
                              name='visible',
                              field=models.BooleanField(default=True),
                          )]),
        migrations.AlterField(
            model_name='klass',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunSQL("""UPDATE "data_klass" SET "visible" = false WHERE "name" = 'user_profile'""", "")
    ]
