# coding=UTF8
from django.urls import path

from apps.core.routers import NestedSimpleRouter
from apps.webhooks.v1 import views

router = NestedSimpleRouter()

webhook_router = router.register('webhooks', views.WebhookViewSet, base_name='webhook')

webhook_router.register(
    'traces',
    views.WebhookTraceViewSet,
    base_name='webhook-trace',
    parents_query_lookups=[
        'webhook',
    ]
)

urlpatterns = [
    path('webhooks/p/<public_link>/<name>/',
         views.WebhookPublicView.as_view(),
         name='webhook-public-run-with-name'),
    # Deprecated but left for compatibility. As links are generated by us, it should be relatively safe to remove
    # after some time.
    path('webhooks/p/<public_link>/',
         views.WebhookPublicView.as_view(),
         name='webhook-public-run'),
]

urlpatterns += router.urls
