# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:10
import django.contrib.postgres.fields
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='channel',
            name='_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='channel',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='acl',
            field=apps.core.fields.NullableJSONField(blank=True, default={}, null=True),
        ),
        migrations.RunSQL("""
CREATE INDEX channel_acl_users ON channels_channel
USING GIN (_users);

CREATE INDEX channel_acl_groups ON channels_channel
USING GIN (_groups);

CREATE INDEX channel_acl_public ON channels_channel
USING BTREE (_public) WHERE _public = true;
"""),
    ]
